{"name": "test_contactus_form_send", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:299:16", "trace": "self = <tests.test_contactus_page.TestContactUsPage object at 0x03AB8400>\n\n    @pytest.mark.runthis\n    @allure.story(\"Проверка корректной отправки формы обратной связи\")\n    def test_contactus_form_send(self):\n        \"\"\"Verifying that contact us form sends successfully\"\"\"\n        contact_us = ContactUsPage(self.driver)\n>       contact_us.attach_txt_file(str(Path(pathlib.Path.cwd() / 'ContactUs form.txt')))\n\ntests\\test_contactus_page.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\contactus_page.py:15: in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\nbase\\seleniumbase.py:29: in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"8eaf7d75-ceaf-416b-8762-da8660d8d82a\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x03A608E0>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nE       element.find/</<@chrome://remote/content/marionette/element.js:299:16\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "description": "Verifying that contact us form sends successfully", "steps": [{"name": "Прикрепление файла", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:299:16\n\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\pages\\contactus_page.py\", line 15, in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\base\\seleniumbase.py\", line 29, in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 89, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "file_path", "value": "'C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\ContactUs form.txt'"}], "start": 1642592497731, "stop": 1642592508043}], "attachments": [{"name": "Screenshot", "source": "af0190e4-65ac-453f-b616-89a2e30765c0-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "2860795b-0e2a-415f-a6fd-868ad0ade481-attachment.txt", "type": "text/plain"}], "start": 1642592496816, "stop": 1642592508053, "uuid": "52c0e4e2-60df-4e07-bacf-4e7fc96a14e3", "historyId": "eec3f3bdb32471cd8a64ec4144811604", "testCaseId": "5eee35e243bc5160f7cb10f7b5804ad4", "fullName": "tests.test_contactus_page.TestContactUsPage#test_contactus_form_send", "labels": [{"name": "story", "value": "Проверка корректной отправки формы обратной связи"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "Тест формы обратной связи"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_driver_init')"}, {"name": "tag", "value": "runthis"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contactus_page"}, {"name": "subSuite", "value": "TestContactUsPage"}, {"name": "host", "value": "ArtemKozlov"}, {"name": "thread", "value": "6192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contactus_page"}]}