{"uuid": "f22a1198-99e2-4f32-9a71-86378b9b0ff5", "children": ["37a3121f-bb72-4346-95b0-59fc703a3a2b"], "befores": [{"name": "web_driver_init", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\tests\\conftest.py\", line 63, in web_driver_init\n    print(request.cls)\n  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 495, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1641987414814, "stop": 1641987425756}], "start": 1641987414814, "stop": 1641987427456}