{"name": "test_contactus_form_error", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:299:16", "trace": "self = <tests.test_contactus_page.TestContactUsPage object at 0x03C66CD0>\n\n    @allure.story(\"Проверка появления ошибки при отправки формы обратной связи с незаполненным полем 'Message'\")\n    def test_contactus_form_error(self):\n        \"\"\"Verifying that error message appears if Message area is empty\"\"\"\n        contact_us = ContactUsPage(self.driver)\n>       contact_us.attach_txt_file(str(Path(pathlib.Path.cwd() / 'ContactUs form.txt')))\n\ntests\\test_contactus_page.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\contactus_page.py:15: in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\nbase\\seleniumbase.py:29: in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"1ae10840-9f0d-4f90-ac5a-91d15774a579\")>\nmethod = <function presence_of_element_located.<locals>._predicate at 0x03C89148>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except InvalidSelectorException as e:\n                raise e\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nE       element.find/</<@chrome://remote/content/marionette/element.js:299:16\n\n..\\..\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:89: TimeoutException"}, "description": "Verifying that error message appears if Message area is empty", "steps": [{"name": "Прикрепление файла", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.jsm:393:5\nelement.find/</<@chrome://remote/content/marionette/element.js:299:16\n\n", "trace": "  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\pages\\contactus_page.py\", line 15, in attach_txt_file\n    self._is_present(\"xpath\", ContactUsPageLocators.choose_file_button).send_keys(file_path)\n  File \"C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\base\\seleniumbase.py\", line 29, in _is_present\n    return self.__wait.until(ec.presence_of_element_located((self.__get_selenium_by(find_by), locator)))\n  File \"C:\\Users\\Artem Kozlov\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 89, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "file_path", "value": "'C:\\Users\\Artem Kozlov\\PycharmProjects\\POM_Selenium_Pytest_Task1\\ContactUs form.txt'"}], "start": 1642510338798, "stop": 1642510349210}], "attachments": [{"name": "Screenshot", "source": "7114c708-25e4-4d42-9664-80ee319d1023-attachment.png", "type": "image/png"}], "start": 1642510337935, "stop": 1642510349210, "uuid": "58fd10a7-2214-4440-979f-4beb5ac9b42e", "historyId": "3afa3963dd0ea7e6116d37ac1b81cb63", "testCaseId": "0419b764a652c09b017d94f58deb9b97", "fullName": "tests.test_contactus_page.TestContactUsPage#test_contactus_form_error", "labels": [{"name": "feature", "value": "Тест формы обратной связи"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "Проверка появления ошибки при отправки формы обратной связи с незаполненным полем 'Message'"}, {"name": "tag", "value": "@pytest.mark.usefixtures('web_driver_init')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_contactus_page"}, {"name": "subSuite", "value": "TestContactUsPage"}, {"name": "host", "value": "ArtemKozlov"}, {"name": "thread", "value": "1448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_contactus_page"}]}